server:
  port: 8080

spring:
  application:
    name: order-ms
  
  datasource:
    # Usa variables de entorno con valores por defecto para desarrollo local
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bodrido_orders_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 'update' crea/actualiza tablas automáticamente. En prod usa 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración para Feign Clients (comunicación entre microservicios)
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

jwt:
  public-key-path: classpath:keys/ec_public.pem # Ruta a la llave pública