services:
  # Servicio de Base de Datos
  order-db:
    image: postgres:16-alpine
    container_name: bodrido-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bodrido_orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-ms:
    build: .
    container_name: bodrido-order-ms
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=order-db  # Nombre del servicio de arriba
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bodrido_orders_db
    depends_on:
      - order-db

volumes:
  postgres_data: