services:
  postgres:
    image: postgres:15-alpine
    container_name: fleetservice_postgres
    environment:
      POSTGRES_USER: fleetUser
      POSTGRES_PASSWORD: fleetPass123
      POSTGRES_DB: FleetDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fleet_network

  fleetservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetservice_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5433;Database=FleetDB;Username=fleetUser;Password=fleetPass123"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - fleet_network

volumes:
  postgres_data:

networks:
  fleet_network:
    driver: bridge
